#pring.jpa.show-sql: true
spring:
  jpa:
    hibernate:
      # preserve DB across restarts (default value is create-drop)
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: UTC
  datasource:
    # save to file, default is save in memory
    url: jdbc:h2:file:./target/air-quality-hackathon-project
  h2:
    # enable H2 database web interface
    console:
      enabled: true
      path: /system/db
logging:
  level:
    bg.startit: DEBUG
air-quality:
  email:
    apiKey: ${EMAIL_API_KEY:"n/a"}
    senderEmail: ${SENDER_EMAIL:airquality@startit.bg}
    senderName: ${SENDER_NAME:Air Quality App}
